name: Check Updates

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  terramate:
    name: Terramate
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Check for a newer Terramate version
        run: ./scripts/check-terramate-version.sh

  hadolint:
    name: Hadolint
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Check for a newer Hadolint version
        run: ./scripts/check-hadolint-version.sh
